from util.settings import Settings


class Constants:
    BATTLEGROUND_WIDTH = 100
    BATTLEGROUND_HEIGHT = 100
    SCROLL_STEP = 0.1
    UPSCALE_BOUND = 30
    DOWNSCALE_BOUND = int(2.25 * BATTLEGROUND_WIDTH)
    FONT_REGULAR = 50
    FONT_LOGO = 80
    FONT_SMALL = 40
    LINE_WIDTH = 1
    CURSOR_ON_TIME = 850
    CURSOR_OFF_TIME = 720
    COLOR_BUTTON_WIDTH = 50
    PRESSED_COLOR_WIDTH = 40
    FRAME_WIDTH = 64
    RATIO = BATTLEGROUND_WIDTH / BATTLEGROUND_HEIGHT
    CANVAS_WIDTH = Settings.screen_width
    CANVAS_HEIGHT = int(CANVAS_WIDTH / RATIO)
    CLICK_DEAD_ZONE = 0

